add_rules("mode.debug", "mode.release")

set_languages("c++23")

--xmake f --cxx=g++ --cc=gcc -m release --debugger=lldb
--xmake project -k compile_commands

--add_requires("libomp")
--add_requires("libtorch")

target("icecream")
    set_kind("headeronly")
    --add_includedirs("$(projectdir)/icecream-cpp", {public = true})
    add_includedirs("$(projectdir)/my_icecream", {public = true})


task("build matplot++")
    on_run(function()
        fl = os.exec("sh matplot_build.sh")
    end)

target("boost_interpolate")
    set_kind("headeronly")
    add_includedirs("interpolate_from_boost", {public = true})

target("matplot++_external")
    set_kind("headeronly")
    --on_load(function(target)
        --#include("core.base.task")
        --task.run("build matplot++")
    --end)
    --add_headerfiles("$(projectdir)/matplotplusplus/source/matplot/matplot.h", {public = true})
    --add_headerfiles("$(projectdir)/matplotplusplus/source/3rd_party/nodesoup/include/nodesoup.h", {public = true})
    add_includedirs("matplotplusplus/build/local/source/matplot", {public = true})
    add_includedirs("matplotplusplus/source", {public = true})
    add_includedirs("matplotplusplus/source/3rd_party/nodesoup", {public = true})
    
    --add_headerfiles("$(projectdir)/matplotplusplus/build/local/_deps/glad-build/include/glad/glad.h", {public = true})
    --add_headerfiles("$(projectdir)/matplotplusplus/build/local/_deps/glad-build/include/KHR/khrplatform.h", {public = true})
    

    add_links("$(projectdir)/matplotplusplus/build/local/source/matplot/libmatplot.a", {public = true})
    --add_links("$(projectdir)/matplotplusplus/build/local/source/matplot/libmatplot_opengl.a", {public = true})
    add_links("$(projectdir)/matplotplusplus/build/local/source/3rd_party/libnodesoup.a", {public = true})
    --add_links("$(projectdir)/matplotplusplus/build/local/_deps/glad-build/libglad.a", {public = true})


target("pocketfft")
    set_kind("headeronly")
    --add_headerfiles("pocketfft/pocketfft_hdronly.h", {public = true})
    add_includedirs("pocketfft", {public = true})


target("non-parametric_dsp")
    set_kind("headeronly")
    --add_headerfiles("src/npdsp_concepts.hpp", "src/signals.hpp", "src/derivators.hpp",
    --        "src/integrators.hpp", "src/filters.hpp", "src/inst_freq_computers.hpp",
    --        "src/utility_math.hpp", "src/approximators.hpp", "src/config.hpp", 
    --        "src/phase_computers.hpp", "src/inst_ampl_computers.hpp"
    --        ,"src/modes_extractors.hpp", {public = true}
    --        )
    add_includedirs("np_dsp", {public = true})

    add_deps("pocketfft")
    add_deps("matplot++_external")
    add_deps("icecream")
    add_deps("boost_interpolate")
    add_cxxflags("--fp_mode=strict")

target("signals-tokenizer")
    set_kind("headeronly")
    --add_headerfiles("src/encodings_generator.hpp")
    add_includedirs("tokenizer", {public = true})
    add_deps("non-parametric_dsp")
    --add_deps("libomp")
    --add_deps("libtorch")

--target("torch-base-example")
    --set_kind("binary")
    --add_files("examples/torch/dcgan.cpp")
    --add_deps("non-parametric_dsp")
    --add_deps("pocketfft")
    --add_deps("matplot++_external")

target("fft-example")
    set_kind("binary")
    add_files("examples/utility/fft/main.cpp")
    add_deps("non-parametric_dsp")
    add_deps("pocketfft")
    add_deps("matplot++_external")


target("fft-experiments")
    set_kind("binary")
    add_files("examples/utility/fft/experiments.cpp")
    add_deps("non-parametric_dsp")
    add_deps("pocketfft")
    add_deps("matplot++_external")

target("theta_loss_check")
    set_kind("binary")
    add_files("examples/utility/fft/cos_theta_loss.cpp")
    add_deps("matplot++_external")

target("ampl_loss_check")
    set_kind("binary")
    add_files("examples/utility/fft/cos_ampl_loss.cpp")
    add_deps("matplot++_external")

target("generic_signal_example")
    set_kind("binary")
    add_files("examples/signals/generic_signal.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("riman_integral_example")
    set_kind("binary")
    add_files("examples/integrators/riman.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("finnite_difference_example")
    set_kind("binary")
    add_files("examples/derivators/finnite_difference.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("fs_based_approx_example")
    set_kind("binary")
    add_files("examples/approximators/fourier_series_based.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("inst_freq_computer_derivative_example")
    set_kind("binary")
    add_files("examples/inst_freq_computers/derivative_based.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("inst_freq_computer_extremums_example")
    set_kind("binary")
    add_files("examples/inst_freq_computers/extremums_based.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("inst_freq_computer_extr_opt_example")
    set_kind("binary")
    add_files("examples/inst_freq_computers/extr_opt.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("filtering_non_opt_perod_based")
    set_kind("binary")
    add_files("examples/filters/non_opt_period_based.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("extremums_based_phase_computer")
    set_kind("binary")
    add_files("examples/phase_computers/extremums_based.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("phase_based_inst_freq_computer")
    set_kind("binary")
    add_files("examples/inst_freq_computers/phase_based.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")

target("filtering_opt")
    set_kind("binary")
    add_files("examples/filters/opt_filter.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("inst_ampl_computeng_inst_freq_and_der_based")
    set_kind("binary")
    add_files("examples/inst_ampl_computers/derivative_and_inst_freqs_based.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("my_fft_ifft_example")
    set_kind("binary")
    add_files("examples/utility_math/fft.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("my_fast_conv_example")
    set_kind("binary")
    add_files("examples/utility_math/convolution.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")


target("main_extractor_example")
    set_kind("binary")
    add_files("examples/modes_extractors/main.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")


target("arctg_experiments")
    set_kind("binary")
    add_files("examples/utility/arctg_exp.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")


target("filtering_reqursive_example")
    set_kind("binary")
    add_files("examples/filters/reqursive.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("filtering_non_opt_value_based")
    set_kind("binary")
    add_files("examples/filters/non_opt_value_based.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("filtering_cascade")
    set_kind("binary")
    add_files("examples/filters/cascade_filter.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("opt_filtering_cascade")
    set_kind("binary")
    add_files("examples/filters/opt_cascade_filter.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("inst_ampl_normalizer")
    set_kind("binary")
    add_files("examples/inst_ampl_computers/inst_ampl_norm.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("reqursive_opt_filtering")
    set_kind("binary")
    add_files("examples/filters/req_opt_filter.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("inst_freq_normalizer")
    set_kind("binary")
    add_files("examples/utility_math/inst_freq_norm.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("filtering_non_opt_average_based")
    set_kind("binary")
    add_files("examples/filters/non_opt_average_based.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("naive_inst_ampl_req_example")
    set_kind("binary")
    add_files("examples/inst_ampl_computers/inst_ampl_norm_req.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("hilbert_transform")
    set_kind("binary")
    add_files("examples/utility_math/ht.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("ht_inst_ampl_computer")
    set_kind("binary")
    add_files("examples/inst_ampl_computers/ht_based.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("conv_filter")
    set_kind("binary")
    add_files("examples/filters/conv_filter.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("sinc_filter")
    set_kind("binary")
    add_files("examples/filters/sinc.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("weighted_ht")
    set_kind("binary")
    add_files("examples/filters/weighted_ht.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("gaussian_filter")
    set_kind("binary")
    add_files("examples/filters/gaussian_filter.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("circle_extend_example")
    set_kind("binary")
    add_files("examples/utility_math/circle_extend.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("sinc_local_filter")
    set_kind("binary")
    add_files("examples/filters/sinc_local.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("inst_freq_norm_sinc_tokenizer")
    set_kind("binary")
    add_files("examples/tokenizers/inst_freq_norm_sinc.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("sinc_res_full_filter_example")
    set_kind("binary")
    add_files("examples/filters/sinc_res_full.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("sinc_res_req_full_filter_example")
    set_kind("binary")
    add_files("examples/filters/sinc_res_req_filter.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("sinc_res_req_extractor_example")
    set_kind("binary")
    add_files("examples/modes_extractors/inst_freq_norm_req.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("sinc_res_req_tokenizer_example")
    set_kind("binary")
    add_files("examples/tokenizers/inst_freq_norm_sinc_req.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("orthogonality_test")
    set_kind("binary")
    add_files("examples/modes_extractors/orthogonality_test.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("makima_approximator_example")
    set_kind("binary")
    add_files("examples/approximators/makima.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("phase_pchip_approx_experiment")
    set_kind("binary")
    add_files("examples/phase_computers/pchip_experient.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")

target("extremums_pchip_based_phase_computer")
    set_kind("binary")
    add_files("examples/phase_computers/extremums_pchip_based.cpp")
    add_deps("matplot++_external")
    add_deps("non-parametric_dsp")
    add_deps("icecream")